/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deals
         * @description Lists deals for the authenticated organization. Open deals only by
         *     default; pass `include_terminal=true` to include won/lost.
         */
        get: operations["listDeals"];
        put?: never;
        /** Create a deal */
        post: operations["createDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{dealId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        /** Get a deal */
        get: operations["getDeal"];
        put?: never;
        post?: never;
        /** Delete a deal */
        delete: operations["deleteDeal"];
        options?: never;
        head?: never;
        /**
         * Update a deal
         * @description Partial update. **Stage is not changed here** — use
         *     `POST /deals/{dealId}/stage-change` so the move is audited.
         *     Invoice link ids are read-only and set only by handoff.
         */
        patch: operations["updateDeal"];
        trace?: never;
    };
    "/deals/{dealId}/stage-change": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a deal to another stage
         * @description Moves the deal to `to_stage_id` and records a DealStageHistory entry
         *     (actor derived from auth). Moving into a terminal **won** stage does
         *     **not** auto-trigger the Invoice handoff — that is a separate, explicit
         *     operator action. (scope-contract X9)
         */
        post: operations["changeDealStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{dealId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        /**
         * List stage-change history for a deal
         * @description Audit-lite stage history, newest first. (scope-contract D7)
         */
        get: operations["listDealStageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{dealId}/invoice-handoff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand off a won deal to NeNe Invoice (draft client + quote)
         * @description Operator-confirmed handoff. Deal calls NeNe Invoice over HTTP to create
         *     a **draft** client and a **draft** quote, then persists
         *     `invoice_client_id` and `invoice_quote_id` (link ids only).
         *
         *     **Preconditions** (invoice-handoff-contract.md): deal is in the terminal
         *     won stage, has `account_label` and `amount_cents`, and is not already
         *     linked.
         *
         *     **Idempotency**: send an `Idempotency-Key` header to make retries safe.
         *     A repeat on an already-linked deal returns `409` with the existing link
         *     unless the same key is replayed, which returns the original `200`.
         *
         *     Upstream Invoice failures leave the deal **won but unlinked**; no partial
         *     link is written. Invoice remains billing SSOT after handoff.
         */
        post: operations["invoiceHandoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pipeline stages
         * @description Ordered pipeline stages for the organization (kanban column order).
         *     Seeded defaults: lead, qualified, proposal, negotiation, won, lost.
         *     Stage customization UI is Phase 2. (terminology.md, roadmap.md)
         */
        get: operations["listStages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kanban board (stages with their open deals)
         * @description Read model for the kanban view: one column per stage with its open
         *     deals and per-column totals. Terminal stages are excluded unless
         *     `include_terminal=true`.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly weighted forecast (approximate)
         * @description Weighted landing for a calendar month: open deals whose
         *     `expected_close_date` falls in the month, summed as
         *     `amount_cents * probability_percent / 100`. Approximate — not a
         *     billing or revenue figure. (scope-contract D4, terminology.md)
         */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ULID identifier (Crockford base32, 26 chars).
         * @example 01ARZ3NDEKTSV4RRFFQ69G5FAV
         */
        Ulid: string;
        /**
         * Format: int64
         * @description Amount in JPY minor units (cents). No floats.
         * @example 150000000
         */
        AmountCents: number;
        Deal: {
            id: components["schemas"]["Ulid"];
            /** @description Tenant scope; derived from the authenticated principal. */
            readonly organization_id: string;
            /** @description Buyer display name until an Invoice client exists. */
            account_label: string;
            amount_cents: components["schemas"]["AmountCents"];
            stage_id: components["schemas"]["Ulid"];
            /** @description Convenience copy of the current stage slug. */
            readonly stage_slug?: string;
            /** @description Win likelihood (0–100). */
            probability_percent: number;
            /**
             * Format: date
             * @description Optional forecast hint.
             */
            expected_close_date?: string | null;
            owner_user_id?: string | null;
            /** @description Short note; not a CRM activity feed. */
            note?: string | null;
            /**
             * Format: int64
             * @description NeNe Invoice client PK; set only after handoff.
             */
            readonly invoice_client_id?: number | null;
            /**
             * Format: int64
             * @description NeNe Invoice quote PK; set only after handoff.
             */
            readonly invoice_quote_id?: number | null;
            /** Format: date-time */
            readonly handoff_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DealCreate: {
            account_label: string;
            amount_cents: components["schemas"]["AmountCents"];
            /** @description Target stage as ULID or slug. */
            stage_id: string;
            /** @description Defaults to the stage's default probability if omitted. */
            probability_percent?: number;
            /** Format: date */
            expected_close_date?: string | null;
            owner_user_id?: string | null;
            note?: string | null;
        };
        /** @description Partial update. Stage and Invoice link ids are excluded. */
        DealUpdate: {
            account_label?: string;
            amount_cents?: components["schemas"]["AmountCents"];
            probability_percent?: number;
            /** Format: date */
            expected_close_date?: string | null;
            owner_user_id?: string | null;
            note?: string | null;
        };
        DealList: {
            data: components["schemas"]["Deal"][];
            /** @description Cursor for the next page; null when no more results. */
            next_cursor?: string | null;
        };
        StageChangeRequest: {
            /** @description Destination stage as ULID or slug. */
            to_stage_id: string;
            /** @description Optional override; otherwise the stage default applies. */
            probability_percent?: number;
        };
        PipelineStage: {
            id: components["schemas"]["Ulid"];
            readonly organization_id: string;
            /**
             * @description Stable key for client-side i18n labels (e.g. `proposal`).
             * @example proposal
             */
            slug: string;
            /** @description Server default display label; UI localizes by slug (ja/en). */
            label: string;
            /** @description Kanban column order (ascending). */
            sort_order: number;
            /** @description True for won/lost. */
            is_terminal: boolean;
            /** @description True only for the won stage. */
            is_won: boolean;
        };
        StageHistoryEntry: {
            id: components["schemas"]["Ulid"];
            deal_id: components["schemas"]["Ulid"];
            /** @description ULID; null when the deal was created at this stage. */
            from_stage_id?: string | null;
            to_stage_id: components["schemas"]["Ulid"];
            actor_user_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        KanbanBoard: {
            columns: components["schemas"]["KanbanColumn"][];
        };
        KanbanColumn: {
            stage: components["schemas"]["PipelineStage"];
            deals: components["schemas"]["Deal"][];
            deal_count: number;
            total_cents: components["schemas"]["AmountCents"];
            weighted_total_cents: components["schemas"]["AmountCents"];
        };
        ForecastSummary: {
            /** @example 2026-06 */
            month: string;
            open_deal_count: number;
            /** @description Unweighted sum of amount_cents for in-month open deals. */
            pipeline_total_cents: components["schemas"]["AmountCents"];
            /** @description Sum of amount_cents * probability_percent / 100 (approximate). */
            weighted_total_cents: components["schemas"]["AmountCents"];
            by_stage: components["schemas"]["ForecastStageBucket"][];
        };
        ForecastStageBucket: {
            stage_id: components["schemas"]["Ulid"];
            slug: string;
            deal_count: number;
            total_cents: components["schemas"]["AmountCents"];
            weighted_total_cents: components["schemas"]["AmountCents"];
        };
        /**
         * @description Optional handoff body. Empty body is valid; the deal's own fields drive
         *     the draft. Reserved for future optional hints (e.g. address fields,
         *     Phase 2). Deal sends draft resources only.
         */
        InvoiceHandoffRequest: {
            /**
             * @description Optional explicit confirmation flag for clients that send one.
             * @default true
             */
            confirm: boolean;
        };
        InvoiceHandoffResult: {
            deal_id: components["schemas"]["Ulid"];
            /**
             * Format: int64
             * @description Draft client PK in NeNe Invoice.
             */
            invoice_client_id: number;
            /**
             * Format: int64
             * @description Draft quote PK in NeNe Invoice.
             */
            invoice_quote_id: number;
            /** Format: date-time */
            handoff_at: string;
            handoff_actor_user_id?: string | null;
        };
        /** @description RFC 7807 Problem Details. type = https://nene-deal.dev/problems/{slug} */
        Problem: {
            /**
             * Format: uri
             * @example https://nene-deal.dev/problems/validation-failed
             */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Malformed request (e.g. bad query parameter). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found in this organization. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Deal ULID. */
        DealId: components["schemas"]["Ulid"];
        /** @description Max items per page. */
        Limit: number;
        /** @description Opaque pagination cursor from a previous response. */
        Cursor: string;
        /** @description Client-generated key making the handoff retry-safe. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDeals: {
        parameters: {
            query?: {
                /** @description Filter by current stage (ULID or slug). */
                stage_id?: string;
                /** @description Filter by deal owner. */
                owner_user_id?: string;
                /** @description Case-insensitive substring match on account_label. */
                q?: string;
                /** @description Include deals in terminal stages (won/lost). */
                include_terminal?: boolean;
                /** @description Max items per page. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of deals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createDeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreate"];
            };
        };
        responses: {
            /** @description Deal created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealUpdate"];
            };
        };
        responses: {
            /** @description Updated deal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    changeDealStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageChangeRequest"];
            };
        };
        responses: {
            /** @description Deal after the move. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listDealStageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stage-change history entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StageHistoryEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    invoiceHandoff: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key making the handoff retry-safe. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Deal ULID. */
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InvoiceHandoffRequest"];
            };
        };
        responses: {
            /** @description Handoff completed; deal now linked to Invoice draft resources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceHandoffResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /**
             * @description Deal already linked to Invoice, or not eligible (e.g. not in won
             *     stage). Problem Details carries guidance and any existing link ids.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Preconditions not met (missing amount/account_label, or not won). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description NeNe Invoice returned an error or was unreachable; deal left unlinked. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listStages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered stages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PipelineStage"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBoard: {
        parameters: {
            query?: {
                /** @description Limit cards to a single owner. */
                owner_user_id?: string;
                include_terminal?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kanban board. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanbanBoard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getForecast: {
        parameters: {
            query: {
                /** @description Target calendar month, `YYYY-MM`. */
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast summary for the month. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
