export type { DealId } from './ids'
export { toDealId } from './ids'
export type { CreateDealInput, Deal, InvoiceHandoffResult, UpdateDealInput } from './model'
export { dealKeys } from './query-keys'
export { useDeal } from './queries'
export { useChangeDealStage, useCreateDeal, useInvoiceHandoff, useUpdateDeal } from './mutations'
export type { ChangeDealStageVars, UpdateDealVars } from './mutations'
