<?php

declare(strict_types=1);

namespace NeneDeal\Tests\Audit;

use NeneDeal\Audit\AuditCsvHandler;
use NeneDeal\Audit\AuditExportRepositoryInterface;
use NeneDeal\Audit\AuditExportRow;
use NeneDeal\Audit\ExportAuditUseCase;
use Nyholm\Psr7\Factory\Psr17Factory;
use PHPUnit\Framework\TestCase;

/**
 * Covers the audit CSV export now that it is generated by
 * `Nene2\Export\CsvWriter` (NENE2 v1.8.0): the UTF-8 BOM and header schema are
 * preserved, formula injection in attacker-controlled `before`/`after` values is
 * neutralised, and the payload round-trips back through `str_getcsv`.
 */
final class AuditCsvHandlerTest extends TestCase
{
    private const BOM = "\xEF\xBB\xBF";

    public function test_export_emits_bom_and_header_schema(): void
    {
        $body = $this->export([]);

        self::assertStringStartsWith(self::BOM, $body, 'UTF-8 BOM must precede the header row.');
        self::assertStringContainsString(
            'timestamp,actor,action,deal_id,field,before,after',
            $body,
            'Header schema (order and names) must be preserved.',
        );
    }

    public function test_export_neutralises_formula_injection_in_before_after(): void
    {
        $row = new AuditExportRow(
            createdAt: '2026-07-06 10:00:00',
            action: 'updated',
            dealId: 'deal-1',
            dealLabel: 'ACME',
            actorLabel: 'alice@example.com',
            fromStageLabel: null,
            toStageLabel: null,
            changes: [
                'title' => ['from' => '=cmd|\'/c calc\'!A1', 'to' => '+SUM(A1:A9)'],
            ],
        );

        $body = $this->export([$row]);

        // Leading formula triggers are prefixed with a single quote so a
        // spreadsheet renders the cell as text instead of executing it.
        self::assertStringContainsString("'=cmd", $body);
        self::assertStringContainsString("'+SUM(A1:A9)", $body);
        // The dangerous forms must no longer appear unquoted as a full cell.
        self::assertStringNotContainsString(',=cmd', $body);
        self::assertStringNotContainsString(',+SUM(A1:A9)', $body);
    }

    public function test_export_round_trips_and_preserves_column_values(): void
    {
        $row = new AuditExportRow(
            createdAt: '2026-07-06 10:00:00',
            action: 'updated',
            dealId: 'deal-1',
            dealLabel: 'ACME',
            actorLabel: 'alice@example.com',
            fromStageLabel: null,
            toStageLabel: null,
            changes: [
                // A value that is benign but contains a comma and a quote,
                // exercising RFC 4180 quoting on the round trip.
                'note' => ['from' => 'old, "quoted"', 'to' => 'new value'],
            ],
        );

        $body = $this->export([$row]);
        $lines = $this->dataLines($body);

        self::assertCount(1, $lines);
        $fields = str_getcsv($lines[0], ',', '"', '');

        self::assertSame(
            ['2026-07-06 10:00:00', 'alice@example.com', 'updated', 'deal-1', 'note', 'old, "quoted"', 'new value'],
            $fields,
        );
    }

    /** @param list<AuditExportRow> $rows */
    private function export(array $rows): string
    {
        $psr17 = new Psr17Factory();
        $handler = new AuditCsvHandler(
            new ExportAuditUseCase(new FakeAuditExportRepository($rows)),
            $psr17,
        );

        $request = $psr17->createServerRequest('GET', '/api/v1/audit/export')
            ->withQueryParams(['from' => '2026-07-01', 'to' => '2026-07-31']);

        $response = $handler->handle($request);

        self::assertSame(200, $response->getStatusCode());
        self::assertSame('text/csv; charset=UTF-8', $response->getHeaderLine('Content-Type'));

        return (string) $response->getBody();
    }

    /**
     * Data rows (BOM stripped, header dropped), skipping the trailing empty
     * element produced by the final line terminator.
     *
     * @return list<string>
     */
    private function dataLines(string $body): array
    {
        $body = substr($body, strlen(self::BOM));
        $lines = array_values(array_filter(
            explode("\n", str_replace("\r\n", "\n", trim($body))),
            static fn (string $line): bool => $line !== '',
        ));

        array_shift($lines); // header

        return $lines;
    }
}

/**
 * In-memory audit export read model returning a fixed set of rows regardless of
 * the requested range.
 */
final readonly class FakeAuditExportRepository implements AuditExportRepositoryInterface
{
    /** @param list<AuditExportRow> $rows */
    public function __construct(private array $rows)
    {
    }

    public function findInRange(string $startDateTime, string $endDateTime): array
    {
        return $this->rows;
    }
}
